# Generated by Django 2.2.12 on 2021-09-24 21:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardPack',
            fields=[
                ('PackID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=20, unique=True)),
                ('creationDate', models.DateField(auto_now=True)),
                ('public', models.BooleanField()),
                ('approved', models.BooleanField()),
                ('rating', models.IntegerField(blank=True, default=0)),
                ('numberOfCards', models.IntegerField()),
                ('sourceLanguage', models.CharField(choices=[('EN', 'English'), ('RU', 'Russian')], max_length=2)),
                ('targetLanguage', models.CharField(choices=[('EN', 'English'), ('RU', 'Russian')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('FlashCardID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sourceText', models.TextField(max_length=100)),
                ('ImageID', models.TextField(max_length=50)),
                ('targetText', models.TextField(max_length=100)),
                ('sourceAudio', models.TextField(max_length=50)),
                ('targetAudio', models.TextField(max_length=50)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.CardPack')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('SubscriptionID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('expiration', models.DateField()),
                ('started', models.DateField()),
                ('paymentMethod', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], max_length=4)),
                ('paymentInfo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('TierID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('monthlyPrice', models.IntegerField()),
                ('maxReviewsPerDay', models.IntegerField()),
                ('communityPacksAvailable', models.BooleanField()),
                ('maxLanguages', models.IntegerField()),
                ('pictures', models.BooleanField()),
                ('discountWithPackContribution', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Username', models.CharField(max_length=40, unique=True)),
                ('registrationDate', models.DateField(auto_now=True)),
                ('registrationService', models.CharField(choices=[('go', 'Google'), ('no', 'No')], max_length=2)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('paswordHash', models.CharField(max_length=40, null=True)),
                ('XP_points', models.PositiveIntegerField(default=0)),
                ('subsctiptionID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Subscription')),
            ],
        ),
        migrations.CreateModel(
            name='UserPackStatus',
            fields=[
                ('PackStatusID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('progress', models.IntegerField(blank=True, default=0)),
                ('startDate', models.DateField(auto_now=True)),
                ('PackID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.CardPack')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Users')),
            ],
        ),
        migrations.CreateModel(
            name='UserCardStatus',
            fields=[
                ('CardStatusID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cardStrength', models.FloatField(default=0)),
                ('lastReviewedTime', models.DateField()),
                ('firstReviewedTime', models.DateField()),
                ('CardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.FlashCard')),
                ('PackStatusIP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.UserPackStatus')),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='Tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.SubscriptionTier'),
        ),
        migrations.AddField(
            model_name='cardpack',
            name='createBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Users'),
        ),
    ]
